### ISSUE TITLE
Adding environment variables breaks startup process?

### ISSUE THREAD

**Issue by andredasilvapinto** [CenturyLinkLabs/docker-gitlab#2]
After adding environment variables for SMTP and saving the changes I'm not facing an infinite loop of failures to start this image:

```
Jun 20 20:59:45 systemd Started GitLab.service.
Jun 20 20:59:45 docker Status: Image is up to date for centurylink/gitlab:7.3.0
Jun 20 20:59:46 docker Creating SSH2 RSA key; this may take some time ...
Jun 20 20:59:46 docker Creating SSH2 DSA key; this may take some time ...
Jun 20 20:59:46 docker Creating SSH2 ECDSA key; this may take some time ...
Jun 20 20:59:46 docker Creating SSH2 ED25519 key; this may take some time ...
Jun 20 20:59:47 docker invoke-rc.d: policy-rc.d denied execution of restart.
Jun 20 20:59:48 docker sed: -e expression #1, char 18: unknown option to `s'
Jun 20 20:59:48 systemd GitLab.service: main process exited, code=exited, status=1/FAILURE
Jun 20 20:59:48 docker Error response from daemon: No such container: GitLab
Jun 20 20:59:48 docker time="2015-06-20T18:59:48Z" level="fatal" msg="Error: failed to stop one or more containers"
Jun 20 20:59:48 systemd Unit GitLab.service entered failed state.
Jun 20 20:59:48 systemd GitLab.service failed.
...
```

**Comment by andredasilvapinto** [comment]
Seems that the relevant line is:

```
Jun 20 20:59:48 docker sed: -e expression #1, char 18: unknown option to `s'
```

as after removing the strange characters ("%-.") from the SMTP_PASS environment variable, the container started without any problem, even though it still printed the _invoke-rc.d: policy-rc.d denied execution of restart._ message.

Before getting it to work, I had to rename the container to Gitlab_2 as I was also getting an error that there was a Gitlab container already, even though the only one is itself. Seems that somewhere there are references of old container versions that are not being removed...

**Comment by sameersbn** [comment]
@andredasilvapinto Some characters need to be escaped in bash. It is not possible to handle such cases in the scripts. Best I found is avoid using `&`, `%`, `/`, etc. characters that mess with command line.

Use `docker ps -a` to list all running and stopped containers. Remove the stopped containers that you don't need `docker rm -f gitlab`. You cannot name two containers the same (includes stopped containers).

**Comment by andredasilvapinto** [comment]
Thanks for your reply.

Regarding the duplicated names, yes that was the reason, but that should have been dealt with by Panamax. I just changed an environment variable and said to restart the application, there was only one gitlab container in the Web UI, so I was expecting Panamax to avoid creating duplicated containers - like it usually does - even if the start process of the container breaks. I guess this is probably a Panamax bug though.
